name: WakaTime status update 

on:
  push:
    branches: [ main ]
  schedule:
    # 7am EST
    - cron: '0 12 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      # Use avinal/Profile-Readme-WakaTime@<latest-release-tag> for latest stable release
      # Do not change the line below until you have forked this repository
      # If you have forked this project you can use <username>/Profile-Readme-WakaTime@master instead
      - uses: avinal/Profile-Readme-WakaTime@master, lowlighter/metrics@v3.3
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          # Branch - newer GitHub repositories have "main" as default branch, change to main in that case, default is master
          BRANCH: "main"
          # Manual Commit messages - write your own messages here
          COMMIT_MSG: "Updated profile time"
      - uses: lowlighter/metrics@v3.3
        with:
          # ... other options
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_languages_details: bytes-size, percentage
          description: Additional details
          type: array
          format: comma-separated
